export const BOOKS_REQUEST = "BOOKS_REQUEST";
export const BOOKS_SUCCESS = "BOOKS_SUCCESS";
export const BOOKS_FAIL = "BOOKS_FAIL";

export const BOOK_DETAUIL_REQUEST = "BOOK_DETAUIL_REQUEST";
export const BOOK_DETAUIL_SUCCESS = "BOOK_DETAUIL_SUCCESS";
export const BOOK_DETAUIL_FAIL = "BOOK_DETAUIL_FAIL";

export const BOOK_SEARCH = "BOOK_SEARCH";
