export const BOOKS_REQUEST = "BOOKS_REQUEST";
export const BOOKS_SUCCESS = "BOOKS_SUCCESS";
export const BOOKS_FAIL = "BOOKS_FAIL";

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";

export const BOOK_SEARCH = "BOOK_SEARCH";
