export const MUSIC_REQUEST = "MUSIC_REQUEST";
export const MUSIC_SUCCESS = "MUSIC_SUCCESS";
export const MUSIC_FAIL = "MUSIC_FAIL";

export const MUSIC_DETAILS_REQUEST = "MUSIC_DETAILS_REQUEST";
export const MUSIC_DETAILS_SUCCESS = "MUSIC_DETAILS_SUCCESS";
export const MUSIC_DETAILS_FAIL = "MUSIC_DETAILS_FAIL";

export const MUSIC_SEARCH = "MUSIC_SEARCH";
