export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const CHANGE_SELECTED_LANGUAGES = "CHANGE_SELECTED_LANGUAGES";
