import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { musicList } from "../store/actions/musicActions";
import MusicItem from "../components/MusicItem";

const MusicPage = () => {
  // const dispatch = useDispatch();

  // const { music } = useSelector((state) => state.musicList);
  // console.log(music);

  // useEffect(() => {
  //   dispatch(musicList());
  // }, [dispatch]);

  const testMusic = [
    {
      id: 1,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1697325320142-28beaededbf3",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 2,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1696595861023-35fde5406cb2",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 3,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1692035072849-93a511f35b2c",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 4,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1695917642455-8ee7e1ce83db",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 5,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1697325320142-28beaededbf3",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 6,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1696595861023-35fde5406cb2",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 7,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1692035072849-93a511f35b2c",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 8,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1695917642455-8ee7e1ce83db",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 9,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1697325320142-28beaededbf3",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 10,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1696595861023-35fde5406cb2",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 11,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1692035072849-93a511f35b2c",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 12,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1695917642455-8ee7e1ce83db",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 13,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1697325320142-28beaededbf3",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 14,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1696595861023-35fde5406cb2",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 15,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1692035072849-93a511f35b2c",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 16,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1695917642455-8ee7e1ce83db",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 17,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1697325320142-28beaededbf3",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 18,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1696595861023-35fde5406cb2",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 19,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1692035072849-93a511f35b2c",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 20,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1695917642455-8ee7e1ce83db",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 21,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1697325320142-28beaededbf3",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 22,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1696595861023-35fde5406cb2",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 23,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1692035072849-93a511f35b2c",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 24,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1695917642455-8ee7e1ce83db",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 25,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1697325320142-28beaededbf3",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 26,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1696595861023-35fde5406cb2",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 27,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1692035072849-93a511f35b2c",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 28,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1695917642455-8ee7e1ce83db",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 29,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1697325320142-28beaededbf3",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 30,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1696595861023-35fde5406cb2",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 31,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1692035072849-93a511f35b2c",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
    {
      id: 32,
      language: "English",
      isLiked: false,
      image: "https://images.unsplash.com/photo-1695917642455-8ee7e1ce83db",
      title: "Lorem",
      author: "Ipsum",
      length: "4:37",
    },
  ];

  return (
    <div className="flex h-full w-full flex-wrap gap-4 overflow-y-auto">
      {testMusic.map((item) => (
        <MusicItem {...item} key={item.id} />
      ))}
    </div>
  );
};

export default MusicPage;
