# Generated by Django 4.2.5 on 2023-09-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='app_lang',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_language', to='baseApp.language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='learning_langs',
            field=models.ManyToManyField(null=True, to='baseApp.language'),
        ),
    ]
