# Generated by Django 4.2.5 on 2023-09-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='learning_langs',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='app_lang',
            field=models.OneToOneField(default='English', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='app_language', to='baseApp.language'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_langs',
            field=models.ManyToManyField(to='baseApp.language'),
        ),
    ]
