# Generated by Django 4.2.5 on 2023-09-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_language_remove_userprofile_learning_langs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
