# Generated by Django 4.2.5 on 2023-09-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_alter_userprofile_app_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='app_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_language', to='baseApp.language'),
        ),
    ]
